--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/aieuo/Mineflow
projects:
  Mineflow:
    path: ""
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.1.0
...
