name: Mineflow
main: aieuo\mineflow\Main
version: 2.5.3
api: [4.0.0]
load: POSTWORLD
mcpe-protocol:
  - 475
  - 471
  - 465
softdepend:
  - EconomyAPI
  - MoneySystem
  - PocketMoney
  - if
author: aieuo
permissions:
  mineflow.command.mineflow:
    default: op
    description: "mineflow.command.mineflow"
  mineflow.customcommand.op:
    default: op
    description: "mineflow.customcommand.op"
  mineflow.customcommand.true:
    default: true
    description: "mineflow.customcommand.true"
