---
name: Mineflow
main: aieuo\mineflow\Main
version: 0.3.0
api: 3.0.0
mcpe-protocol:
  - 389
  - 390
load: POSTWORLD
softdepend:
  - EconomyAPI
  - MoneySystem
  - PocketMoney
  - if
  - ReplenishResources
author: aieuo
permissions:
  mineflow.command.mineflow:
    default: op
    description: "mineflow.command.mineflow"
  mineflow.customcommand.op:
    default: op
    description: "mineflow.customcommand.op"
  mineflow.customcommand.true:
    default: true
    description: "mineflow.customcommand.true"
...