name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
  - type: textarea
    id: crash-dump
    attributes:
      label: Crash dump
      description: If you have a crash dump, please copy and paste it. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of mineflow are you running?
    validations:
      required: true
  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: If you are not sure, you can find it using the `/var` command.
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      value: "8.0"
    validations:
      required: true
  - type: input
    id: server-os
    attributes:
      label: Server OS
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Please attach screenshots or exported files of relevant recipes if any.
